### ISSUE TITLE
How to chain together calls?

### ISSUE THREAD

**Issue by Qqwy** [peterszerzo/elm-porter#4]
Hello there! Porter is a wonderful library, and it definitely makes working with Elm's 0.18 (and upcoming 0.19)'s restrictions to interfacing with JavaScript a lot less painful.

I am attempting to perform a couple of Porter calls in sequence before these are mapped back to my main Msg; similar to `Http.andThen`, `Task.andThen` etc.

Is this currently possible or would it require a small change to the way response handlers are used?

**Comment by peterszerzo** [comment]
@Qqwy thank you for your interest, and happy to hear that the library is useful.

Chaining is currently not supported, but it would be a great next step for the library - in fact, it would make my life easier in an app I am currently working on. I will research the API over the course of next week, but it looks like having an opaque `Request` type that you can build on would be best, so exactly as you suggest with `andThen`, you can send something like this:

```elm
Porter.request "apple"
  |> Porter.andThen (\response -> Porter.request (response ++ "!"))
  -- Note that this is different from `send`, which is a shorthand for a direct send
  |> Porter.sendRequest ResponseHandler
```

What do you think? I'll also look at `map2`, `map3` etc. Stay tuned!

**Comment by Qqwy** [comment]
Yes, this is exactly it! :slightly_smiling_face: 

Let me know if I can help!

**Comment by peterszerzo** [comment]
Sure - I will ping you for a code review when it's ready :)
