### ISSUE TITLE
Idea: make PorterMsg part of the configuration

### ISSUE THREAD

**Issue by Qqwy** [peterszerzo/elm-porter#5]
Currently, the user of this library has to write  `Sub.map PorterMsg` and `Cmd.map PorterMsg` for every time he calls `Porter.send` somewhere.

I think it might be possible to hide this implementation detail a little more by making it part of the configuration. `Porter.subscriptions` already accepts the configuration as a parameter, so it would be able to just call into that.

`Porter.send` does not yet, which would make this a backwards-incompatible change, but I think it would make sense to accept the configuration as the first argument. This would also allow a user to wrap and name `Porter.send someConfiguration`, which makes it even nicer to use.

In a similar idea, one might specify the accessor method to the Porter field inside the model (like `.porter`) as part of the configuration, which would mean that the way `Porter.update` alters the model could be abstracted away from the user as well.

This means that the user only would have to type:

```elm

type alias Model =
    { my_porter_location : Porter.Model String String Msg
    , response : String
    }

port outgoing : Encode.Value -> Cmd msg
port incoming : (Decode.Value -> msg) -> Sub msg

porter config = 
    { outgoingPort = outgoing
    , incomingPort = incoming
    , encodeRequest = Encode.string
    , decodeRequest = Decode.string
    , porterMsg = MyPorterMsg
    , porterAccessor = .my_porter_location
    }

type Msg
    = OtherMsg String
     | MyPorterMsg (Porter.Msg String String Msg)

update msg model = 
    case msg of
       MyPorterMsg porter_msg ->
           Porter.update porterConfig porter_msg model 
        OtherMsg foo ->
            ...

subscriptions model = 
    Porter.subscriptions porterConfig
```

to set up porter.

**Comment by peterszerzo** [comment]
This looks really good - adding `porterMsg` in there will go a long way simplifying the setup.

As far as `porterAccessor` is concerned, it doesn't seem like the implementation is doable in Elm. Even if we have access to the `porterAccessor = .my_porter_location` function inside the config, that still won't allow us to do `{ model | [porterAccessor] = newPorter }` like in JS (not to mention if the accessor is more complicated). We'd have to expect a separate `porterSetter` method as well, which feels more complicated than doing it explicitly in the update a single time in the app.

**Comment by peterszerzo** [comment]
Also, are you interested in tackling this?

**Comment by Qqwy** [comment]
Yes, I'll give it a shot! Expect a PR somewhere this coming week :-).

**Comment by peterszerzo** [comment]
Always feel free to ping me on Elm slack to discuss (same goes for anyone interested in this project) - it's the same `peterszerzo` name.
