### ISSUE TITLE
Possibility for map, map2, map3, ... ?

### ISSUE THREAD

**Issue by Qqwy** [peterszerzo/elm-porter#8]
So, after spending a couple of hours with the new `andThen` implementation, I realized that when writing a library, it is nice to expose concrete types as responses of the called functions to the user. (In practice, because of network failure and because we do not want to trust JS more than required, these types will be types like  `Result ErrorType String`, `Result ErrorType Bool`, `Result ErrorType Int`).

Obviously, the API under the hood uses one single data type representation for the calls, and one single datatype for all responses (which means there is exactly one port-pair required). In my case, this is the 'Web3 Ethereum JSON-RPC API '. (The exact API I am consuming is [this one](https://github.com/ethereum/wiki/wiki/JSON-RPC)).

However, to specialize the response types (which is a lot nicer than the user receiving `SomeResponseType` and having to handle whatever is returned themselves), we need to be able to specify a `responseHandler` function at request-creation time.

In the old API, this was no problem. We'd use the `msg` type for this result, and pass the proper `res -> msg` function as argument to the `Porter.send` function.

But in the new API, `send` and `request` have been split. There is no way to pass a `responseHandler` to a `Porter.request` call. However, in this example, I'd like to do:

```
user type 
-> (converted by Porter.Config.encodeRequest) req 
-> outgoing port 
-> JS 
-> incoming port 
-> (converted by Porter.Config.decodeRequest) res 
-> (converted by special response handler supplied to this specific request) specialzed_res 
-> (user-supplied response handler to Porter.send) msg
```

Maybe this is a way we could implement `Porter.map`: append a stage to the 'special response handler'?

This would turn the type of `Porter.map` into something like:

```elm
map : (resA -> resB) -> Request req inner_res resA -> Request req inner_res resB

```
(where chaining this directly to an `andThen` is obviously only possible when `reqA` === `reqB`)

---

_I just came back from a very long day, but I did want to write this down now so you have some extra time to look at it, since this change will probably be not be able to be made in a backwards-compatible way._

**Comment by peterszerzo** [comment]
Fixed in #9. Thanks @Qqwy for all the great work!
